### PR TITLE
Support class based test functions

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Thanks!

**Comment by s0undt3ch** [comment]
Got any plans for when to release this fix?

**Comment by KimiNewt** [comment]
I'd also like a new release for this fix :)

**Comment by eugeniy** [comment]
New version is up https://pypi.python.org/pypi/pytest-tornado

Thanks for the fix!

**Comment by s0undt3ch** [comment]
Awesome! Thanks!

**Pull request merged**
