### PR TITLE
plugin: Put custom CLI options in "tornado" group

### PR DESCRIPTION
**Pull request by allanlewis**
Previously, the command-line options were added to the default group, labelled "custom options" by Pytest. This commit puts the options in a group labelled "tornado options", separating them from other options in order to make it clear where they come from. This is especially useful in environments where multiple plugins are used.

### CODE REVIEW

**Comment by okin** [comment]
I think this is a good idea. 
@vidartf any chance on getting this merged?

**Comment by vidartf** [comment]
Agreed, seems useful.

**Comment by vidartf** [comment]
This PR seems broken/corrupted somehow. I cannot merge here because of conflicts, and I cannot find its source branch/repo anywhere. Is this something we can salvage somehow, or should this be resubmitted (attribution to original author will be lost)?

**Comment by allanlewis** [comment]
I must have deleted my fork 😢 
I'll see if I can recover it somehow.

**Comment by allanlewis** [comment]
Replaced by #53.

**Pull request closed without merging**
